pipeline {
    agent any

    stages {
        stage ('Print NodeJS and NPM') {
            steps {
                sh '''
                node -v
                npm -v
                '''
            }
        }
    }
}